
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class Form_Laundry extends javax.swing.JFrame {

    /**
     * Creates new form Form_Laundry
     */
    public Form_Laundry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Berat = new javax.swing.JTextField();
        HargaR = new javax.swing.JTextField();
        Bayar = new javax.swing.JTextField();
        HargaL = new javax.swing.JTextField();
        Jenis = new javax.swing.JComboBox<>();
        Batal = new javax.swing.JButton();
        Transaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laundry Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 300, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Harga Per Kilo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Berat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Total Harga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Bayar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 120, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Jenis Cuci");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 30));

        Berat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Berat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeratActionPerformed(evt);
            }
        });
        Berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BeratKeyReleased(evt);
            }
        });
        jPanel1.add(Berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 30));

        HargaR.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        HargaR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HargaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaRActionPerformed(evt);
            }
        });
        jPanel1.add(HargaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 200, 30));

        Bayar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Bayar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });
        jPanel1.add(Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 200, 30));

        HargaL.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        HargaL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HargaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaLActionPerformed(evt);
            }
        });
        jPanel1.add(HargaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 30));

        Jenis.setEditable(true);
        Jenis.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Cuci Kering", "Cuci Basah", "Cuci Setrika" }));
        Jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisActionPerformed(evt);
            }
        });
        jPanel1.add(Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 200, 30));

        Batal.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Batal.setText("Batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });
        jPanel1.add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 130, -1));

        Transaksi.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Transaksi.setText("Transaksi");
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 130, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 510, 720);

        setSize(new java.awt.Dimension(514, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeratActionPerformed

    private void HargaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaRActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BayarActionPerformed

    private void HargaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaLActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        Jenis.setSelectedItem("Pilih");
        HargaL.setText("");
        Berat.setText("");
        HargaR.setText("");
        Bayar.setText("");
    }//GEN-LAST:event_BatalActionPerformed

    private void JenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisActionPerformed
        if(Jenis.getSelectedItem().toString().equalsIgnoreCase("Cuci Kering")){
            HargaL.setText("5000");
        }else if(Jenis.getSelectedItem().toString().equalsIgnoreCase("Cuci Basah")){
            HargaL.setText("10000");
        }else if(Jenis.getSelectedItem().toString().equalsIgnoreCase("Cuci Setrika")){
            HargaL.setText("15000");
        }
    }//GEN-LAST:event_JenisActionPerformed

    private void BeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BeratKeyReleased
        int hargal = Integer.parseInt(HargaL.getText());
        int berat  = Integer.parseInt(Berat.getText());
        Integer hargar = hargal*berat;
        String total = Integer.toString(hargar);
        HargaR.setText(total);
    }//GEN-LAST:event_BeratKeyReleased

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        int bayar = Integer.parseInt(Bayar.getText());
        int hargar = Integer.parseInt(HargaR.getText());
        double kembalian = bayar - hargar;
        String kembali = Double.toString(kembalian);
        JOptionPane.showMessageDialog(null,"Kembalian Anda : \n"+kembali);
        
        Jenis.setSelectedItem("Pilih");
        HargaL.setText("");
        Berat.setText("");
        HargaR.setText("");
        Bayar.setText("");
    }//GEN-LAST:event_TransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Laundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JTextField Bayar;
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField HargaL;
    private javax.swing.JTextField HargaR;
    private javax.swing.JComboBox<String> Jenis;
    private javax.swing.JButton Transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
